<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-U61ILI3" failures="1" tests="3" name="Default test" time="20.129" errors="0" timestamp="2024-01-05T11:22:37 IST">
  <testcase classname="source.TestClass" name="ValidateOrdersList" time="1.777"/>
  <testcase classname="source.TestClass" name="error" time="1.373"/>
  <testcase classname="source.TestClass" name="submitOrder" time="0.012">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
[public void source.TestClass.submitOrder(java.util.HashMap) throws java.io.IOException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: submitOrder([java.util.HashMap&amp;lt;java.lang.String, java.lang.String&amp;gt; arg0])
Arguments: [(java.lang.String) 12344@gmail.com,(java.lang.String) Vishwa123,(java.lang.String) ZARA COAT 3]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void source.TestClass.submitOrder(java.util.HashMap) throws java.io.IOException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: submitOrder([java.util.HashMap<java.lang.String, java.lang.String> arg0])
Arguments: [(java.lang.String) 12344@gmail.com,(java.lang.String) Vishwa123,(java.lang.String) ZARA COAT 3]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:909)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:37)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- submitOrder -->
</testsuite> <!-- Default test -->
